import React from 'react'
import Home from '../page'
import styles from '@/app/ui/about/about.module.css'

export default function About() {
    return (
        <div>
            <Home />
            <section className={styles.about}>
                <h1>About-Us</h1>
                <div className={styles.info}>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque fugiat accusantium velit, placeat adipisci nihil in suscipit, facere quis eaque pariatur cum. Atque aut eaque illo, labore quibusdam tempore perspiciatis aliquam! Deserunt possimus temporibus enim, aspernatur voluptatibus quasi laboriosam, commodi nesciunt voluptatum ut corporis quidem laudantium fugiat quod. Voluptatum dicta non exercitationem aliquid tenetur assumenda sit hic culpa vero voluptate, eum consequuntur eveniet accusamus facere expedita vitae animi pariatur quibusdam? Earum qui fugit, doloribus quidem laboriosam repudiandae possimus labore deleniti sunt laborum non quae nesciunt ratione temporibus et. Atque magni a provident quibusdam aspernatur facere numquam unde nesciunt eius ipsa dolore iusto eligendi molestiae quam placeat aut magnam sunt doloremque veritatis sed, corrupti doloribus est? Repellat eaque reiciendis ipsa similique.</p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque fugiat accusantium velit, placeat adipisci nihil in suscipit, facere quis eaque pariatur cum. Atque aut eaque illo, labore quibusdam tempore perspiciatis aliquam! Deserunt possimus temporibus enim, aspernatur voluptatibus quasi laboriosam, commodi nesciunt voluptatum ut corporis quidem laudantium fugiat quod. Voluptatum dicta non exercitationem aliquid tenetur assumenda sit hic culpa vero voluptate, eum consequuntur eveniet accusamus facere expedita vitae animi pariatur quibusdam? Earum qui fugit, doloribus quidem laboriosam repudiandae possimus labore deleniti sunt laborum non quae nesciunt ratione temporibus et. Atque magni a provident quibusdam aspernatur facere numquam unde nesciunt eius ipsa dolore iusto eligendi molestiae quam placeat aut magnam sunt doloremque veritatis sed, corrupti doloribus est? Repellat eaque reiciendis ipsa similique.</p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque fugiat accusantium velit, placeat adipisci nihil in suscipit, facere quis eaque pariatur cum. Atque aut eaque illo, labore quibusdam tempore perspiciatis aliquam! Deserunt possimus temporibus enim, aspernatur voluptatibus quasi laboriosam, commodi nesciunt voluptatum ut corporis quidem laudantium fugiat quod. Voluptatum dicta non exercitationem aliquid tenetur assumenda sit hic culpa vero voluptate, eum consequuntur eveniet accusamus facere expedita vitae animi pariatur quibusdam? Earum qui fugit, doloribus quidem laboriosam repudiandae possimus labore deleniti sunt laborum non quae nesciunt ratione temporibus et. Atque magni a provident quibusdam aspernatur facere numquam unde nesciunt eius ipsa dolore iusto eligendi molestiae quam placeat aut magnam sunt doloremque veritatis sed, corrupti doloribus est? Repellat eaque reiciendis ipsa similique.</p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque fugiat accusantium velit, placeat adipisci nihil in suscipit, facere quis eaque pariatur cum. Atque aut eaque illo, labore quibusdam tempore perspiciatis aliquam! Deserunt possimus temporibus enim, aspernatur voluptatibus quasi laboriosam, commodi nesciunt voluptatum ut corporis quidem laudantium fugiat quod. Voluptatum dicta non exercitationem aliquid tenetur assumenda sit hic culpa vero voluptate, eum consequuntur eveniet accusamus facere expedita vitae animi pariatur quibusdam? Earum qui fugit, doloribus quidem laboriosam repudiandae possimus labore deleniti sunt laborum non quae nesciunt ratione temporibus et. Atque magni a provident quibusdam aspernatur facere numquam unde nesciunt eius ipsa dolore iusto eligendi molestiae quam placeat aut magnam sunt doloremque veritatis sed, corrupti doloribus est? Repellat eaque reiciendis ipsa similique.</p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque fugiat accusantium velit, placeat adipisci nihil in suscipit, facere quis eaque pariatur cum. Atque aut eaque illo, labore quibusdam tempore perspiciatis aliquam! Deserunt possimus temporibus enim, aspernatur voluptatibus quasi laboriosam, commodi nesciunt voluptatum ut corporis quidem laudantium fugiat quod. Voluptatum dicta non exercitationem aliquid tenetur assumenda sit hic culpa vero voluptate, eum consequuntur eveniet accusamus facere expedita vitae animi pariatur quibusdam? Earum qui fugit, doloribus quidem laboriosam repudiandae possimus labore deleniti sunt laborum non quae nesciunt ratione temporibus et. Atque magni a provident quibusdam aspernatur facere numquam unde nesciunt eius ipsa dolore iusto eligendi molestiae quam placeat aut magnam sunt doloremque veritatis sed, corrupti doloribus est? Repellat eaque reiciendis ipsa similique.</p>
                </div>
            </section>
        </div>
    )
}
